name: Search Console Weekly Report

on:
  schedule:
    - cron: "30 10 * * 3" # 한국 시간(KST): 매주 수요일 오후 7시 30분
  workflow_dispatch: # 수동 실행 옵션 추가

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: pnpm install

      - name: Run report script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        run: pnpm start
